#!/bin/sh

#cleanup

rm -rf obj_dir
rm -f lfsr.vcd

# run verilator to translate verilog -> C++
verilator -Wall --cc --trace lfsr.sv --exe lfsr_tb.cpp

#build C++ project via make automatically generated by verilator
make -j -C obj_dir/ -f Vlfsr.mk Vlfsr

#run executable simulation file
obj_dir/Vlfsr